export interface NewBusinessListPending{
    applicantName?: string,
    buildingNo?: string,
    controlNo?: number,
    dateReceived?: string,
    projectName?: string,
    remarks?: string,
    status?: string,
    address?:string,
    receivedby?:string,
    typeofoccupancy?:string,
    contactno?:string,
    evaluator?:string,
    nostorey?:number,
    constructrenovate?:string,
    structureconstructed?:boolean,
    defects?:string[],
    id?: string,
}

export interface addBusinessPermit{
    applicantName: string,
    buildingNo: string,
    controlNo?: number,
    dateReceived: string,
    projectName: string,
    remarks: string,
    status: string,
    address:string,
    receivedby:string,
    typeofoccupancy:string,
    contactno:string,
    evaluator:string,
    nostorey:number,
    constructrenovate:string,
    structureconstructed:boolean,
    defects:string[],
}