export interface NewBusinessListPending {
    applicantName?: string,
    buildingNo?: string,
    controlNo?: number,
    dateReceived?: string,
    projectName?: string,
    remarks?: string,
    status?: string,
    address?: string,
    receivedby?: string,
    typeofoccupancy?: string,
    contactno?: string,
    evaluator?: string,
    nostorey?: number,
    constructrenovate?: string,
    structureconstructed?: boolean,
    defects?: string[],
    id?: string,
}

export interface addBuildingPermit {
    applicantName: string,
    buildingNo: string,
    controlNo?: number,
    dateReceived: string,
    projectName: string,
    remarks: string,
    status: string,
    address: string,
    receivedby: string,
    typeofoccupancy: string,
    contactno: string,
    evaluator: string,
    nostorey: number,
    constructrenovate: string,
    structureconstructed: boolean,
    defects: string[],
}

export interface businessPermit {
    address?: string,
    amount?: number,
    businessname?: string,
    businessno?: string,
    contactno?: string,
    date?: string,
    dateinspection?: string,
    datereceived?: string,
    email?: string,
    fireinspectors?: string[],
    fsicdate?: string,
    fsicno?: number,
    inspection_no?: number,
    naturebusiness?: string,
    orno?: number,
    permittee?: string,
    recommendation?: string[],
    remarks?: string,
    teamleader?: string,
    typeoccupancy?: string,
    id: string,
}

export interface addbusinessPermit {
    address: string,
    amount: number,
    businessname: string,
    businessno: string,
    contactno: string,
    date: string,
    dateinspection: string,
    datereceived: string,
    email: string,
    fireinspectors: string[],
    fsicdate: string,
    fsicno: number,
    inspection_no: number,
    naturebusiness: string,
    orno: number,
    permittee: string,
    recommendation: string[],
    remarks: string,
    teamleader: string,
    typeoccupancy: string,
}
        